quarkus:
  http:
    port: 8080
  log:
    level: INFO
  hibernate-orm:
    dialect: org.hibernate.dialect.MySQLDialect
    log:
      sql: true
    database:
      generation: drop-and-create
  datasource:
    db-kind: mysql
    jdbc:
      max-size: 16
      min-size: 2
app:
  # Variables con valores por defecto que se pueden sobreescribir con env vars
  name: ${APP_NAME:MiAppQuarkus}
  version: ${APP_VERSION:1.0.0}
  environment: ${APP_RUNTIME_ENV:local}
  profile: 'sin definir'
  alias: 'microservicio x'